[[StarData]]
name = "Betelgeuse"
description = "Alpha Orionis"
position = [1.0, 0.0, 0.0]
type = 1


[[StarData]]
name = "Sirius"
description = "Alpha Canis Majoris"
position = [0.0, 1.0, 0.0]
type = 1

 [[StarData]]
name = "Canopus"
description = "Alpha Carinae"
position = [0.0, 0.0, 1.0]
type = 1


[[StarData]]
name = "Rigil Kentaurus"
description = "Alpha Kentaurus"
position = [0.4, 0.2, 0.7]
type = 1

[[StarData]]
name = "Arcturus"
description = "Alpha Bootes"
position = [0.5, 0.5, 0.5]
type = 1

 [[StarData]]
name = "Vega"
description = "Alpha Lyrae"
position = [0.6, 0.3, 0.8]
type = 1

 [[StarData]]
name = "Capella"
description = "Alpha Aquilae"
position = [0.7, 0.4, 0.9]
type = 1


[[StarData]]
name = "Aldebaran"
description = "Alpha Tauri"
position = [-0.8, 0.5, 0.1]
type = 1

 [[StarData]]
name = "Deneb"
description = "Alpha Scorpii"
position = [0.9, 0.6, 0.2]
type = 1


[[StarData]]
name = "Rukbat"
description = "Alpha Geminorum"
position = [0.1, -0.7, 0.3]
type = 1


[[StarData]]
name = "Alphard"
description = "Alpha Pegasi"
position = [0.2, -0.8, -0.4]
type = 1